name: Deploy Node.js App to AWS EC2

on:
  push:
    branches:
      - master  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Pulls your repo code

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Matches your app's Node version

    - name: Install dependencies
      run: npm install  # Installs packages

    - name: Run tests
      run: npm test  # Optional: runs your test suite
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          cd /home/ec2-user/nodejs-demo-app
          git pull origin main
          npm install
          pm2 restart all
